### ISSUE TITLE
Ability to split process multipolygons that my be the result of using antimeridian_splitter

### ISSUE THREAD

**Issue by probinso** [guidorice/antimeridian_splitter#4]
When you run `antimeridian_splitter` and the result is a `multipolygon` we would like to be able to execute `antimeridian_splitter` again without it throwing and error. Currently the program only accepts input of type `polygon`, however it does not throw informative errors when another `geojson` type is passed instead.

**Comment by guidorice** [comment]
Done via https://github.com/guidorice/antimeridian_splitter/pull/5
Thanks 👍🏽
